// AUTO-GENERATED by ProjectFlash_V1.ipynb
`define FLASH_STAGE "V1.2"
`define N_IMAGES 244
`define IMG_H 224
`define IMG_W 224
`define N_PIXELS 50176
`define N_TRACE 8
`define N_ACC 2
`define DEFAULT_THRESHOLD 32'hfffffd7a   // -646
`define REC_ACC_BITS 22
`define REC_MARGIN_BITS 19
