// AUTO-GENERATED by ProjectFlash_V1.ipynb -- do not edit by hand
// stage V1.1, input 28x28

`define LT_WORD_W 128
`define LT_OP_MSB 127
`define LT_OP_LSB 124
`define LT_KERNEL_MSB 123
`define LT_KERNEL_LSB 120
`define LT_STRIDE_MSB 119
`define LT_STRIDE_LSB 116
`define LT_PAD_MSB 115
`define LT_PAD_LSB 112
`define LT_IN_C_MSB 111
`define LT_IN_C_LSB 100
`define LT_OUT_C_MSB 99
`define LT_OUT_C_LSB 88
`define LT_IN_H_MSB 87
`define LT_IN_H_LSB 76
`define LT_IN_W_MSB 75
`define LT_IN_W_LSB 64
`define LT_OUT_H_MSB 63
`define LT_OUT_H_LSB 52
`define LT_OUT_W_MSB 51
`define LT_OUT_W_LSB 40
`define LT_SHIFT_MSB 39
`define LT_SHIFT_LSB 34
`define LT_W_BASE_MSB 33
`define LT_W_BASE_LSB 14
`define LT_B_BASE_MSB 13
`define LT_B_BASE_LSB 4
`define LT_OP_CONV3X3 4'd1
`define LT_OP_GAP 4'd2
`define LT_OP_FC 4'd3

`define FLASH_N_LAYERS 7
`define FLASH_IMG_H 28
`define FLASH_IMG_W 28
`define FLASH_N_WEIGHTS 47432
`define FLASH_N_BIASES 170

// table contents:
//  0: conv1 CONV3X3  1x 28x 28 ->  8x 14x 14  shift  7  w_base      0  b_base   0  word 132100100801c01c00e00e1c00000000
//  1: conv2 CONV3X3  8x 14x 14 -> 16x  7x  7  shift  7  w_base     72  b_base   8  word 132100801000e00e0070071c00120080
//  2: conv3 CONV3X3 16x  7x  7 -> 32x  4x  4  shift  7  w_base   1224  b_base  24  word 13210100200070070040041c01320180
//  3: conv4 CONV3X3 32x  4x  4 -> 48x  2x  2  shift  7  w_base   5832  b_base  56  word 13210200300040040020021c05b20380
//  4: conv5 CONV3X3 48x  2x  2 -> 64x  1x  1  shift  7  w_base  19656  b_base 104  word 13210300400020020010011c13320680
//  5: gap   GAP     64x  1x  1 -> 64x  1x  1  shift  0  w_base      0  b_base   0  word 20000400400010010010010000000000
//  6: fc    FC      64x  1x  1 ->  2x  1x  1  shift  0  w_base  47304  b_base 168  word 3110040002001001001001002e320a80
