// AUTO-GENERATED by ProjectFlash_V1.ipynb
`define FLASH_STAGE "V1.1"
`define N_IMAGES 244
`define IMG_H 28
`define IMG_W 28
`define N_PIXELS 784
`define N_TRACE 8
`define N_ACC 2
`define DEFAULT_THRESHOLD 32'hffffe08e   // -8050
`define REC_ACC_BITS 22
`define REC_MARGIN_BITS 19
