`timescale 1ns / 1ps
//==============================================================================
// tb_top.v -- ProjectFlash V0 regression testbench
//
// Runs N_IMAGES images and checks TWO things per image:
//   1. cancer_detected matches the expected label
//   2. logit0 and logit1 match the Python golden model EXACTLY, bit for bit
//
// (2) is the one that matters. A decision can be right by luck; an exact
// 32-bit logit match proves the RTL datapath and the quantised reference
// model are the same arithmetic.
//
// Inputs generated by the Colab notebook:
//   img_%0d.mem    900 hex bytes each (30x30 zero-padded 28x28 image)
//   exp_label.mem  N lines, 0 or 1
//   exp_logit0.mem N lines, 32-bit two's-complement hex
//   exp_logit1.mem N lines, 32-bit two's-complement hex
//==============================================================================

module tb_top;

    parameter integer N_IMAGES  = 244;
    parameter integer PADDED_W  = 30;
    parameter integer N_PIXELS  = PADDED_W * PADDED_W;   // 900

    reg clk, rst, start;
    reg [7:0] pixel_in;
    reg       pixel_valid;

    wire cancer_detected, result_valid;

    reg  [7:0]  image_mem [0:N_PIXELS-1];
    reg  [7:0]  exp_label  [0:N_IMAGES-1];
    reg  [31:0] exp_logit0 [0:N_IMAGES-1];
    reg  [31:0] exp_logit1 [0:N_IMAGES-1];

    integer k, p, timeout;
    integer n_label_ok, n_logit_ok;
    reg [8*64-1:0] fname;

    reg signed [31:0] got0, got1;

    initial begin clk = 0; forever #5 clk = ~clk; end

    top_accelerator dut (
        .clk(clk), .rst(rst), .start(start),
        .pixel_in(pixel_in), .pixel_valid(pixel_valid),
        .cancer_detected(cancer_detected), .result_valid(result_valid)
    );

    initial begin
        $display("==================================================");
        $display(" ProjectFlash V0 -- %0d-image bit-exactness sweep", N_IMAGES);
        $display("==================================================");

        $readmemh("exp_label.mem",  exp_label);
        $readmemh("exp_logit0.mem", exp_logit0);
        $readmemh("exp_logit1.mem", exp_logit1);

        rst = 1; start = 0; pixel_in = 8'h00; pixel_valid = 0;
        n_label_ok = 0; n_logit_ok = 0;

        repeat (10) @(posedge clk); rst = 0;
        repeat (5)  @(posedge clk);

        for (k = 0; k < N_IMAGES; k = k + 1) begin
            fname = {"img_", 8'h30, ".mem"};          // placeholder, overwritten
            $sformat(fname, "img_%0d.mem", k);
            $readmemh(fname, image_mem);

            repeat (20) @(posedge clk);
            @(negedge clk); start = 1;
            @(negedge clk); start = 0;

            for (p = 0; p < N_PIXELS; p = p + 1) begin
                @(negedge clk);
                pixel_in    = image_mem[p];
                pixel_valid = 1;
            end
            @(negedge clk);
            pixel_valid = 0; pixel_in = 8'h00;

            timeout = 0;
            while (result_valid !== 1'b1 && timeout < 2000000) begin
                @(posedge clk); timeout = timeout + 1;
            end
            if (timeout >= 2000000) begin
                $display("  img %0d: *** TIMEOUT ***", k);
            end else begin
                got0 = dut.logit0;
                got1 = dut.logit1;
                // cancer_flag is registered ON output_valid, so the pin settles
                // one clock AFTER result_valid rises. Sampling it immediately
                // returns the PREVIOUS image's decision.
                repeat (2) @(posedge clk);

                if (cancer_detected === exp_label[k][0])
                    n_label_ok = n_label_ok + 1;

                if (got0 === exp_logit0[k] && got1 === exp_logit1[k]) begin
                    n_logit_ok = n_logit_ok + 1;
                    if (k < 12 || N_IMAGES <= 16)
                        $display("  img %3d  exact  l0=%11d l1=%11d  pred=%0d exp=%0d",
                                 k, $signed(got0), $signed(got1),
                                 cancer_detected, exp_label[k][0]);
                end else begin
                    $display("  img %3d  MISMATCH", k);
                    $display("            rtl    l0=%11d l1=%11d",
                             $signed(got0), $signed(got1));
                    $display("            golden l0=%11d l1=%11d",
                             $signed(exp_logit0[k]), $signed(exp_logit1[k]));
                end
            end
            repeat (4) @(posedge clk);
        end

        $display("--------------------------------------------------");
        $display(" bit-exact logits : %0d / %0d", n_logit_ok, N_IMAGES);
        $display(" label agreement  : %0d / %0d", n_label_ok, N_IMAGES);
        if (n_logit_ok == N_IMAGES)
            $display(" *** RTL IS BIT-EXACT WITH THE GOLDEN MODEL ***");
        else
            $display(" *** %0d IMAGE(S) DIVERGE FROM GOLDEN MODEL ***",
                     N_IMAGES - n_logit_ok);
        $display("==================================================");
        $finish;
    end

    initial begin
        #2000000000;
        $display("*** GLOBAL WATCHDOG TIMEOUT ***");
        $finish;
    end

endmodule
